from numpy import *

arr0=array([1,2,3,4,5])
arr1=array([5.0,-6,7,81,66,-0.0044])
arr2=array([-1.00,25,-30.21,41,53.25,-321.020])
arr3=arr1+arr2
print("")
print("")
# operations in numpy :
print("-------------------------------------------------")
print("")
print("")
arr=array([7,4,3.444,6.10,0.04])
print("1. Array considered is ---> ", arr)
print("")
print("")
print("2. Sine values ---> ",sin(arr))
print("")
print("")
print("3. CoSine values ---> ",cos(arr))
print("")
print("")
print("4. log values ---> ",log(arr))
print("")
print("")
print("5. root values ---> ",sqrt(arr))
print("")
print("")
print("6. sum of values in array ---> ",sum(arr))
print("")
print("")
print("7. Maximum value in array ---> ",max(arr))
print("")
print("")
print("8. Minimum value in array ---> ",min(arr))
print("")
print("")
print("9. sorted array is ---> ",sort(arr))
print("")
print("")
print("10. Concatenated array ---> ",concatenate((arr1, arr2)))
print("")
print("")
print("11. Adding two arrays ---> ",arr3)
print("")
print("")
print("12. Add 5 to each element ---> ",arr+5)
print("")
print("")
print("-------------------------------------------------")
